### ISSUE TITLE
Format: "x11" not recognized. (`plot` / Windows)

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaArchive/Graphs.jl#172]
``` julia
julia> using Graphs

julia> g = simple_graph(4, is_directed=false)
Undirected Graph (4 vertices, 0 edges)

julia> add_edge!(g, 1, 2)
edge [1]: 1 -- 2

julia> add_edge!(g, 1, 4)
edge [2]: 1 -- 4

julia> add_edge!(g, 2, 4)
edge [3]: 2 -- 4

julia> add_edge!(g, 3, 1)
edge [4]: 3 -- 1

julia> add_edge!(g, 3, 2)
edge [5]: 3 -- 2

julia> add_edge!(g, 4, 3)
edge [6]: 4 -- 3

julia> plot(g)

julia> Format: "x11" not recognized. Use one of: bmp canon cmap cmapx cmapx_np dot emf emfplus eps fig gd gd2 gif gv imap imap_np ismap jpe jpeg jpg metafile pdf pic plain plain-ext png pov ps ps2 svg svgz tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.4
```

**Comment by jminardi** [comment]
Same issue on OS X Yosemite 10.10.2

**Comment by wuillou8** [comment]
same for me on yosemite 10.10.3

**Comment by jagrafft** [comment]
Same on Windows 8.

Switching what follows the `-T` command on line 85 of `dots.jl`:

```julia
stdin, proc = open(`neato -Tx11`, "w")
```

From x11 to a GraphViz [Output Format](http://www.graphviz.org/doc/info/output.html) should clean that error up, so long as your system supports the format you choose.

I can't get a plot yet, but that's because I am getting this error now [plot --> Linux #176](https://github.com/JuliaLang/Graphs.jl/issues/176).

**Comment by jbn** [comment]
As a partial solution, I recommend (shamelessly) using my `IJuliaPortrayals` package, at least for interactive `Jupyter`-based work. For example,

```julia
using Graphs
using IJuliaPortrayals

g = simple_complete_graph(10)
GraphViz(to_dot(g), "circo", "svg")
```

**Comment by dmoliveira** [comment]
@jbn: Good work! Nice library!
